In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
x_train.shape

(60000, 28, 28)

In [ ]:
x_test.shape

(10000, 28, 28)

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.07063369, -0.5403057 ,  0.1877278 , -0.13504821,  0.882049  ,
         0.4057337 ,  0.776651  ,  0.47317603,  0.32324505,  0.14271562]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictiaons).numpy()

array([[0.07684042, 0.04171211, 0.08638594, 0.06255517, 0.17297482,
        0.10742906, 0.1556715 , 0.11492423, 0.09892303, 0.08258373]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.2309246

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_traain, epochs=3)

Epoch 1/3
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3022 - accuracy: 0.9119
Epoch 2/3
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1434 - accuracy: 0.9581
Epoch 3/3
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1065 - accuracy: 0.9682


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0815 - accuracy: 0.9737 - 541ms/epoch - 2ms/step


[0.08153123408555984, 0.9736999869346619]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.1648964e-08, 1.0636404e-09, 1.3746664e-05, 2.6800082e-04,
        8.5701578e-11, 5.1904820e-08, 1.1690518e-13, 9.9971694e-01,
        2.4377897e-07, 9.4614455e-07],
       [4.5566503e-06, 4.7024334e-04, 9.9902654e-01, 4.6964368e-04,
        8.2080148e-11, 1.7536478e-05, 3.5620583e-06, 2.3318411e-10,
        7.9237525e-06, 4.2860501e-10],
       [5.6337649e-06, 9.9716228e-01, 1.9842270e-04, 7.0785289e-05,
        1.5555108e-04, 1.7707936e-05, 5.9497863e-05, 1.7517380e-03,
        5.7399110e-04, 4.2606343e-06],
       [9.9674964e-01, 5.0588739e-07, 6.8992277e-04, 1.1030107e-06,
        1.6553148e-04, 2.8399694e-05, 2.2520655e-04, 1.2331342e-03,
        7.9740255e-07, 9.0572686e-04],
       [8.1548897e-06, 1.5596991e-07, 2.7499980e-05, 6.5610287e-08,
        9.9582618e-01, 5.8909459e-06, 5.6378904e-05, 8.3556246e-05,
        6.6847128e-06, 3.9853011e-03]], dtype=float32)>